### ISSUE TITLE
Game crashed after I added this.

### ISSUE THREAD

**Issue by Chill-Me-Diane** [Minenash/Pocketwatch#16]
I removed this because it was making my game crash.
Here is the log:
![image](https://github.com/Minenash/Pocketwatch/assets/172551061/e6766d9f-17c2-435b-9493-938b9cc9e050)

If you can tell me how to easily produce a mod list I'd share that.

If I can figure it out on my own I will send it.

Until then I am using the Fabulously Optimized Fabric 1.20.6 modpack on Modrinth.

Nevermind here is a link to the log.
https://mclo.gs/IFGxZ6o

**Comment by Minenash** [comment]
Unfortunately the log you linked doesn't include pocketwatch. Can you either include the log that does OR tell me the version number of Pocketwatch you're using?

**Comment by Chill-Me-Diane** [comment]
I think I posted the clean version without your mod.

I think this is the one you want.
https://mclo.gs/x9kV15I
Fabric 1.20.6 Server Log [#x9kV15I]<https://mclo.gs/x9kV15I>
423 lines | 3 errors
mclo.gs


________________________________

**Comment by Chill-Me-Diane** [comment]
Hope this helped. I really liked the idea of your mod. If there's anything I can do to help or anything  else I'm ready to try and help.
________________________________

**Comment by Minenash** [comment]
Looks like you have the 1.20/1.20.1 version downloaded instead of the 1.20.5/1.20.6 one
