### ISSUE TITLE
slots not effected by raised

### ISSUE THREAD

**Issue by BeeFox-sys** [Minenash/Pocketwatch#2]
https://modrinth.com/mod/raised

**Comment by Havio1** [comment]
I’d also like to know if there are any plans for supporting this mod, thank you.

**Comment by Minenash** [comment]
Looking at how micriDurability does it, it looks really simple to add (two lines of code, and I don't even have to worry about optional dependencies or anything like that)

**Comment by Minenash** [comment]
Support added in latest modrinth release
