### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Minenash/Pocketwatch#3]
Do you plan on updating the mod, and if it already works would you be able to mark it on modrinth?

**Comment by Minenash** [comment]
Yeah, I'm currently going through all my mods rn. This mod is currently 2nd in the queue for updating. So should probably be done by tomorrow

**Comment by Minenash** [comment]
Updated and released on modrinth

**Comment by Aces-and-Jacks** [comment]
could you mark 1.1.0 as only 1.19.3+ instead of 1.19-1.19.3? It confuses my launcher

**Comment by Minenash** [comment]
... thought I did

**Comment by Minenash** [comment]
Fixed
