### ISSUE TITLE
Could you add Raised support for 1.19.2?

### ISSUE THREAD

**Issue by spunchbop121** [Minenash/Pocketwatch#5]

**Comment by spunchbop121** [comment]
@Minenash

**Comment by mateus3c** [comment]
yeah I was looking for that too :((

**Comment by Minenash** [comment]
Hey, sorry about the lack of ... everything. The semester is done and I have modding time again. Do you guys still care about a 1.19.2 version with 1.19.4 being the latest and 1.20 coming out in a week?

**Comment by spunchbop121** [comment]
1.19.2 will be popular for a long time, so it is advisable to make a port

**Comment by mateus3c** [comment]
yep, 1.19.2 will keep being popular for relatively long time since the mods biggest mods will still take some time to update + some mods wont even update, so I mean, 1.19.2 will still be probably the most popular for the next 5/6 months

**Comment by Minenash** [comment]
Done

**Comment by mateus3c** [comment]
> Done

thank you very much!
