### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by YukiAyase** [Minenash/Pocketwatch#6]
**This was tested in a fresh Minecraft instance with minimal amount of mods**
_Someone had to test it out if the mod works for Minecraft 1.19.4 right?_

Both tested on Quilt and Fabric
Steps to reproduce
1.) Have Pocketwatch 1.1.0+1.19.3 installed _with dependencies_
2.) Put an item inside your inventory whitelisted in Pocketwatch (e.g. compass, clock, etc.)
3.) Crash

Logs
https://mclo.gs/CUmCzE0 (error at line 323)

**Comment by Minenash** [comment]
I haven't updated most of my mods to 1.19.4 yet due to college midterms and projects. I'll get to doing do soon
