### ISSUE TITLE
1.20 and 1.20.1

### ISSUE THREAD

**Issue by ActualBest** [Minenash/Pocketwatch#7]
Love this mod. An ETA for the update would be awesome.

**Comment by zndrmn** [comment]
https://github.com/Minenash/Pocketwatch/tree/1.20
There's been a 1.20 branch for a few days now

**Comment by syns** [comment]
> [https://github.com/Minenash/Pocketwatch/tree/1.20 ](https://github.com/Minenash/Pocketwatch/tree/1.20) There's been a 1.20 branch for a few days now

Could you upload the 1.20 release to Modrinth please? I am sure a lot of other users aren't aware that this mod has been updated. Thanks!
